### ISSUE TITLE
[lecture2][0410] Rotation&Scaling != Scaling&Rotation

### ISSUE THREAD

**Issue by nshuhsn** [PiLab-CAU/ComputerVision-2401#12]
We know that Translating&Scaling is not same as Scaling&Translating.
So I was curious that Rotation&Scaling is also different with Scaling&Rotation

![KakaoTalk_Photo_2024-04-10-14-48-28](https://github.com/PiLab-CAU/ComputerVision-2401/assets/80961346/94f63204-ef8f-4824-8173-4ef274095712)

So Rotation&Scaling != Scaling&Rotation  But if Sx == Sy: can be same

thanks for reading!

**Comment by yjyoo3312** [comment]
@nshuhsn Thanks for reviewing and providing a great example! 
Yes, typically, Rotation & Scaling and Scaling & Rotation yield different results. 
Qualitatively, scaling in the x and y directions before or after rotating would lead to varied outcomes. 
However, this kind of guessing can be confusing (especially to me) in many cases, so it's a good idea to verify these effects through matrix calculations.

**Comment by StevenHSKim** [comment]
@yjyoo3312 @nshuhsn 
I think what you showed is what many people are confused about while doing a 2D transformations.
I was just wondering what it would be like to visualize the above applied to a real image, and I want to share the result.

The first one is about "translating matrix * scaling matrix != scaling matrix * translating matrix"
```python
import cv2
import numpy as np
import matplotlib.pyplot as plt

# 이미지 불러오기
image = cv2.imread('Lenna.png')

# 이미지 크기 가져오기
height, width = image.shape[:2]

# 변환 행렬 생성
tx, ty = 50, 50  # Translating비율
sx, sy = 1.5, 1.5  # Scaling 비율

# Translating * Scaling
translate_scale_matrix = np.float32([[1, 0, tx],
                                     [0, 1, ty],])

scaling_matrix_translate = np.float32([[sx, 0, 0],
                                       [0, sy, 0],])

# 이미지에 변환 적용
translated_scaled_image = cv2.warpAffine(image, translate_scale_matrix, (width, height))
scaled_translated_image = cv2.warpAffine(image, scaling_matrix_translate, (width, height))

# 시각화
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(translated_scaled_image, cv2.COLOR_BGR2RGB))
plt.title('Translating* Scaling')

plt.subplot(1, 2, 2)
plt.imshow(cv2.cvtColor(scaled_translated_image, cv2.COLOR_BGR2RGB))
plt.title('Scaling * Translating')

plt.show()
```
You can see the difference between two images below.
![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/102468317/df44aea8-9f8f-4de7-96e1-687ef52c4e3d)



And second one is about "Scaling matrix * Rotating matrix != Rotating matrix * Scaling matrix "
```python
import cv2
import numpy as np
import matplotlib.pyplot as plt
from math import cos, sin, radians

# 이미지 불러오기
image = cv2.imread('Lenna.png')

# 이미지 크기 가져오기
height, width = image.shape[:2]

# 변환 행렬 생성
angle = 45  # 회전 각도
sx_1, sy_1 = 1.5, 0.8  # scaling1: 각각 다른 scaling 비율
sx_2, sy_2 = 0.8, 0.8  # scaling2: 동일한 scaling 비율

# Rotation Matrix 생성 함수
def rotation_matrix(angle):
    theta = np.radians(angle)
    return np.array([[cos(theta), -sin(theta), 0],
                     [sin(theta), cos(theta), 0],
                     [0, 0, 1]])

# Scaling matrix
scaling_matrix_1 = np.array([[sx_1, 0, 0],
                              [0, sy_1, 0],
                              [0, 0, 1]])

scaling_matrix_2 = np.array([[sx_2, 0, 0],
                              [0, sy_2, 0],
                              [0, 0, 1]])

# Rotation Matrix
R = rotation_matrix(angle)

# 이미지에 변환 적용
scaled_rotated_image_1 = cv2.warpAffine(image, np.dot(scaling_matrix_1, R)[:2], (width, height))
rotated_scaled_image_1 = cv2.warpAffine(image, np.dot(R, scaling_matrix_1)[:2], (width, height))

scaled_rotated_image_2 = cv2.warpAffine(image, np.dot(scaling_matrix_2, R)[:2], (width, height))
rotated_scaled_image_2 = cv2.warpAffine(image, np.dot(R, scaling_matrix_2)[:2], (width, height))

# 시각화
plt.figure(figsize=(12, 6))

plt.subplot(2, 2, 1)
plt.imshow(cv2.cvtColor(scaled_rotated_image_1, cv2.COLOR_BGR2RGB))
plt.title('Scaling 1 * Rotating')

plt.subplot(2, 2, 2)
plt.imshow(cv2.cvtColor(rotated_scaled_image_1, cv2.COLOR_BGR2RGB))
plt.title('Rotating * Scaling 1')

plt.subplot(2, 2, 3)
plt.imshow(cv2.cvtColor(scaled_rotated_image_2, cv2.COLOR_BGR2RGB))
plt.title('Scaling 2 * Rotating')

plt.subplot(2, 2, 4)
plt.imshow(cv2.cvtColor(rotated_scaled_image_2, cv2.COLOR_BGR2RGB))
plt.title('Rotating * Scaling 2')

plt.tight_layout()
plt.show()
```

The result is as follows: as you said, you can see that the results are the same if sx==sy, but different if not.
![image](https://github.com/StevenHSKim/Pytorch-Tutorial/assets/102468317/e3b2e55c-134a-44a4-ba8a-adfa5ab8374e)

Thank you!
HaeSeong Kim
