### ISSUE TITLE
[lecture2][0412] Question about self study

### ISSUE THREAD

**Issue by nshuhsn** [PiLab-CAU/ComputerVision-2401#13]
<img width="794" alt="스크린샷 2024-04-12 오후 12 43 52" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/80961346/0fc3c5a4-f202-40bc-9040-3db6b2229379">

In this problem b is a vector and b1,b2,... is a scalar as far as I understand.
Then I think there should not exist transpose sign in f(x) to make multiplication work!

**Comment by yjyoo3312** [comment]
@nshuhsn Thanks for pointing out the typo! You're correct, and I'll update the material :)

**Comment by yjyoo3312** [comment]
Also, @nshuhsn, could you please email your name to my university address (yjyoo3312@cau.ac.kr) for checking in eClass?
