### ISSUE TITLE
[Lecture2][0415] About Filters and Convolution self study 2

### ISSUE THREAD

**Issue by kimjyan20221186** [PiLab-CAU/ComputerVision-2401#16]
@yjyoo3312, when I'm attempting to solve the self-study materials, specifically on problem 2, I have concerns that the proof regarding shift invariance may not be properly constructed. Could you please advise if the proof I have formulated is sufficient? If not, could you suggest which properties should be utilized?
![photo_2024-04-15_22-45-08](https://github.com/PiLab-CAU/ComputerVision-2401/assets/115198540/6569343c-3011-4b5b-b069-60f37487cc1d)

**Comment by yjyoo3312** [comment]
@kimjyan20221186 Ah, I just saw this now. I will answer it after the class:)

**Comment by yjyoo3312** [comment]
@kimjyan20221186 Sorry for the late reply!

I've attached a sample solution to your question. While it may not meet the strictest standards required in a math class, this answer would still earn a perfect score in my computer vision class (The gray terms would be bit redundant).

![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/12525981/5f5d3d8d-c7d0-4c5a-ab34-c4ad35f5f349)


The overall derivation in this solution is similar to yours, but it uses a more traditional format for clearer mathematical explanation. Typically, especially in math classes, it's advisable to start with a definition and then solve the problem based on that definition. However, I don't view this computer vision course as strictly mathematical, and your answer captures the essential concept needed for the derivation, so I find it acceptable. I will award full marks for the quality of your answer:)

P.S. Could you possibly send your name to my email (yjyoo3312@cau.ac.kr)? It's for the e-class record.

**Comment by kimjyan20221186** [comment]
@yjyoo3312 Thank you for the clear proof! I will send an email soon :)
