### ISSUE TITLE
[Lecture4][0416] Question about difference between Canny edge operator and Harris corner detector

### ISSUE THREAD

**Issue by imsongpasimin** [PiLab-CAU/ComputerVision-2401#17]
@yjyoo3312 Hello Professor, my name is Jeon Yonghyeon, and I am currently enrolled in your class. I am writing to inquire about the reasons behind the differences in the algorithms of the Canny edge operator and the Harris corner detector.

![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/92546000/2916b2db-aa39-43d6-a18e-ba31653b4f6c)

![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/92546000/ebc64d50-aad0-47e5-baf7-ef4d60bd8f91)

In the image aboves, the algorithm for the Canny edge operator applies a Sobel filter to a Gaussian-smoothed image, whereas for the Harris corner detector, it seems that the gradient is first calculated using the Sobel filter, followed by Gaussian smoothing. What is the reason for these differences in the order of operations between the two algorithms?

My hypothesis is that the Harris corner detector necessitates the calculation of the window function (Gaussian smoothing) later in the process due to transformations in the formula. 

![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/92546000/0aebdd46-5cbf-4066-845c-af5af90cf1fa)

However, in Lecture 3, there is an image showing the problems that arise when calculating the gradient before smoothing. Does the Harris corner detector not encounter these problems? Or would it be acceptable for the Canny edge detector to also compute the gradient before applying Gaussian smoothing?

Thanks for watching my issue!

**Comment by kimjyan20221186** [comment]
Although I'm not a professor, I think it's because the purpose of the detector is different. The goal of the Canny edge detector is to find local maxima, which is significantly influenced by noise, while the Harris corner detector seeks points where both gradient x and gradient y change significantly.

**Comment by yjyoo3312** [comment]
@imsongpasimin @kimjyan20221186 Thanks for the question and discussion!

As you guessed, we use Gaussian smoothing in Canny Edge detection to reduce noise, and in the Harris detector, it acts as a window function to accumulate values within the window. This is why we apply Gaussian smoothing before and after Sobel filtering for each case.

If our image is really noisy, particularly with salt and pepper noise, we might need to add another smoothing step before using the Harris corner detector. (For salt and pepper noise, we saw a median filter worked better than a Gaussian filter.)

**Comment by imsongpasimin** [comment]
@yjyoo3312 @kimjyan20221186 Thanks for your advices!
