### ISSUE TITLE
[Lecture1][0418] Regarding the Bhattacharya distance of histograms

### ISSUE THREAD

**Issue by jleem99** [PiLab-CAU/ComputerVision-2401#18]
Hello, @yjyoo3312. My name is JongHan Leem.

Upon reviewing Lecture 1, the part where we discuss the similarity of two images using _Bhattacharya distance_ of their histograms, I noticed that the formula for _Bhattacharya distance_ might be incorrect.

According to the definition of [*Bhattacharyya distance*](https://en.wikipedia.org/wiki/Bhattacharyya_distance#Definition),
The formula for _Bhattacharya distance_ is given by:
$$D_B = -\ln(BC(P,Q))$$

where $BC$ is the _Bhattacharya coefficient_, which is calculated as:
$$BC = \sum_{x \in \mathcal{X}} \sqrt{P(x)Q(x)}$$

However, in the code, the _Bhattacharya coefficient_ is calculated as:
```python
bc = np.sqrt(np.sum(hist1 * hist2))
```

And also, since the _Bhattacharya distance_ measures the similarity between two **probability distributions**, the input histograms should be normalized, such that they can be treated as probability distributions. i.e. the histograms should be normalized using the L1 norm so that the sum of the elements in the histogram is equal to 1. (Currently, the code normalizes histograms using L2 norm)

It might be a subtle thing, but I will create a PR about this!
I also created a Jupyter Notebook file to show some visualizations :)

### Before fix

![histogram_comparison](https://github.com/PiLab-CAU/ComputerVision-2401/assets/23395243/8dc2dead-a478-4e14-adaa-243720ab6527)

### After fix

![histogram_comparison_fixed](https://github.com/PiLab-CAU/ComputerVision-2401/assets/23395243/f64832eb-0230-42f5-ad33-02995b01f301)

**Comment by yjyoo3312** [comment]
@jleem99 
Thank you for the comment, and PR!
 I update the changes regarding the issue, but I will keep open it before the midterm:)
