### ISSUE TITLE
[Lecture1][0307] Fixes in the Lecture

### ISSUE THREAD

**Issue by yjyoo3312** [PiLab-CAU/ComputerVision-2401#2]
Thank you for attending today's course! we have two things to be fixed in the slide.

1. Slides 47-49
<img width="1083" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/12525981/290a4ccc-9b85-42c0-8f4f-d8d7a707f73d">

- After the comment from ..(sorry, I forgot to ask your name), I checked again. 

<img width="273" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/12525981/50e355b5-80f1-4b39-99bb-42a1304d59ab">

- OpenCV depict the pixels in [row, col, channel] order. I always confuse and than you for the comment.

2. Slide 70,71
- The order of sqrt and sqrt has been reversed! Thank you for the comment (sorry, I forgot to ask your name, too).

----------------------------------------------------------------
### How to get alarm

<img width="592" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/12525981/c0ff19a0-ef02-4d4b-9b17-c424b62cfe3a">

**Comment by cjchangjun** [comment]
So, i have to change [125, 137, 226] -> [120, 138, 226] which is value of f(2,4)?

**Comment by yjyoo3312** [comment]
@cjchangjun Yepp! exactly, (as mentioned in https://github.com/PiLab-CAU/ComputerVision-2401/issues/2) the value f(2,4) will be [120, 138, 226].
