### ISSUE TITLE
[Lecture4][0424] Question about the representation in ppt for the SIFT scale

### ISSUE THREAD

**Issue by StevenHSKim** [PiLab-CAU/ComputerVision-2401#22]
I know that the larger the scale, the smaller the image size should be, as shown below.
![image](https://github.com/StevenHSKim/Pytorch-Tutorial/assets/102468317/af74ec9d-9e6e-4a46-b4f2-5f5955332d6f)

I also think that the larger the octave and scale, the smaller the image size should be, as shown below.
![image](https://github.com/StevenHSKim/Pytorch-Tutorial/assets/102468317/e4cdad0c-efd0-4678-93f9-7c6eb6035515)

However, in our PPT, the scale at 0 octave is represented as the largest.
<img width="910" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/102468317/663a7d02-3543-4c55-a388-a1901e6de07c">

I think this problem can be solved by reversing the direction of the arrow for scale.

Is my way of thinking correct?
I apologize if this has already been mentioned in class.

Thank you!
HaeSeong Kim

**Comment by yjyoo3312** [comment]
@StevenHSKim Thank you for the comment:) 
I am often (or frequently) confused about directions, and seems correct.
It would be much correct if I reversed the arrow direction with the caption (scale down).
