### ISSUE TITLE
[lecture9][0502] Convolutional Layers + Activation

### ISSUE THREAD

**Issue by koallako** [PiLab-CAU/ComputerVision-2401#23]
It seems like convolution layers produce the desired number of outputs for the specified kernels without ReLU function. Then, for page 55, what's the necessity of the ReLU function here? I'm curious about what output would be produced if the ReLU function computation is added compared to the output which doesn't contain that function.

Minjung Kim (20210172)

**Comment by yjyoo3312** [comment]
@koallako Thank you for the question! (and apology for the late response)

An activation function such as ReLU is an R->R (real value to real value) function that looks like:

<img width="431" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/12525981/5aca56cf-1e4f-4331-b25f-f17a243a4cba">

We assign the activation function to each element of the output response of the convolutional layer.
This activation function adds non-linearity to our convolutional neural network, which is a crucial factor for the (convolutional and any) neural network design.

In our next lecture, we'll discuss the ReLU activation function in more detail, essential for adding non-linearity to convolutional neural networks. Without ReLU, these networks would merely perform linear operations (maxpool will add some nonlinearity but not enough), insufficient for handling complex image data.
