### ISSUE TITLE
[Lecture10][0507] Small error in the lecture slide

### ISSUE THREAD

**Issue by goals4292** [PiLab-CAU/ComputerVision-2401#25]
I found a really minor error in the lecture slide p25 & p32.

![KakaoTalk_20240508_053701880](https://github.com/PiLab-CAU/ComputerVision-2401/assets/147023917/b30bad57-868b-4bfb-ad14-be2a13eb3a87)

As you can see, PReLU is incorrectly written as 'max(0, x)'.

I think it can be revised as 
'max(x, αx) for α ∈ (0,1)'.

Thank you.
Jaeyung Kim

**Comment by yjyoo3312** [comment]
@goals4292  Oh, Thank you for the comment:) I will correct the typo in the final version
