### ISSUE TITLE
[Lecture11][0517] Is residual block itself leads to an increase in computation?

### ISSUE THREAD

**Issue by StevenHSKim** [PiLab-CAU/ComputerVision-2401#27]
<img width="400" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/102468317/2a5e8524-a417-43ac-93df-bb08647844ef">

I understand the idea of the residual block.

For an input x, the plain block trained on the output, H(x).
However, in the residual block, we define and train a new residual: F(x)+x.

Since it is very difficult to learn the ideal mapping function H(x), we use F(x), which is a slightly more trainable form.
By adding the input x to F(x), the residual method brings stability to the optimization process by learning only the additional information it needs, while retaining what it has already learned.

<img width="400" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/102468317/696f039f-60bf-45ba-b9c3-632068bfcaae">

Intuitively, it seems that adding only x to identical blocks would lead to more computation. 
However, the overall residual network has rather fewer FLOPs.

So my question is:
1. Is it true that "residual blocks themselves" bring optimization stability compared to plain blocks, but lead to an increase in computation?
2. If it's true, is the computation increase in residual blocks largely prevented "only by the bottleneck blocks", so that the overall residual network has a computation decrease?

Thank you!
HaeSeong Kim

**Comment by yjyoo3312** [comment]
@StevenHSKim Thank you for the comment!

1. Yepp, compared to plain blocks with equivalent conv filter settings (c_in, c_out, k_h, k_w), residual block brings dramatic optimization stability, with adding a slight increase of floating point add operation (which is negligible compared to convolution operation).
<img width="398" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/12525981/5b1e7033-4f1b-4403-88a3-14d11140724a">

(see page 40 in lecture slide [10-1](https://drive.google.com/file/d/1MvyaPTg-_upECf8v5lxYxd_IWrVAKIpn/view) ).

2. The key FLOP difference between VGG and ResNet comes from its input and output channel sizes of conv filters for each stage (see page 40 in lecture slide [11](https://drive.google.com/file/d/1AyGKgekITMlSY9hcZIbJMqU3NUSgNN4L/view)), where those of VGG are much larger than ResNet (This is another fancy point of the ResNet compared to VGG, I think).

<img width="404" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/12525981/a2831312-f58e-4698-bf6e-9fd5e1014934">

For example, VGG uses in/out channel size 256 to compute features with resolution (56,56), whereas ResNet uses 64. This will bring about 16 times larger computation accordingly. (So, to make FLOP efficient CNN architecture, it is important to reduce conv channel sizes at the early stages of the network, near the stem conv. why?)

**Comment by StevenHSKim** [comment]
@yjyoo3312 
In my opinion, This is because the initial convolution and pooling layers extract the basic features of the image (edges, color, etc.).
Learning these simple features does not require a relatively large number of filters; using a small number of channels is sufficient and avoids unnecessary redundant computations.

So, to make FLOP efficient CNN architecture, it is important to reduce conv channel sizes at the early stages of the network, near the stem conv.

Thank you!

**Comment by yjyoo3312** [comment]
@StevenHSKim 
Thank you for your opinion :) your supposition "Learning these simple features does not require a relatively large number of filters" can vary between datasets. For example, in face recognition, we know empirically that reducing the channel width doesn't significantly degrade accuracy (even in initial stage of conv layers). However, with a large number of classes, this can become problematic. In FLOP-efficient design, the key factor is that the initial stage of convolutional layers processes high-resolution input feature maps, requiring more convolutional operations than later stages. Therefore, increasing the channel size at the initial stage demands extensive computation, making the design difficult to use in real-world applications. This relates to our discussion on page 33 of the lecture. [11](https://drive.google.com/file/d/1AyGKgekITMlSY9hcZIbJMqU3NUSgNN4L/view).
