### ISSUE TITLE
[Lecture 12][0521] Comparison of the ResNet's and MobileNet v2's block design in PyTorch implementation

### ISSUE THREAD

**Issue by jleem99** [PiLab-CAU/ComputerVision-2401#28]
As professor @yjyoo3312 pointed out in the lecture, one of the key architectural changes in MobileNet v2 is the use of a **linear** bottleneck structure.
So here I examined the official PyTorch implementation of MobileNet v2 and compared it to ResNet.

## ResNet's [Basic Block](https://github.com/pytorch/vision/blob/v0.18.0/torchvision/models/resnet.py#L103C9-L103C29) and [BottleNeck Block](https://github.com/pytorch/vision/blob/v0.18.0/torchvision/models/resnet.py#L161)

<img width="407" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/23395243/0d538a9b-95f0-47dd-910a-25c6359ccb86">

<img width="411" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/23395243/0bb7783b-73ae-42d7-9263-05c41f1d7e5d">

ResNet's block design uses ReLU activation in its output.

## MobileNet v2's [Inverted Residual Block](https://github.com/pytorch/vision/blob/v0.18.0/torchvision/models/mobilenetv2.py#L61-L64)

<img width="402" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/23395243/fba8c3fc-77ba-4608-b1a8-cbcb1040ca18">

As you can see here, MobileNet v2's block does not use an activation function in its final point-wise convolution, employing a linear activation.

<img width="537" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/23395243/fc37715d-79e7-49e7-9124-947a2ceab1c8">

Additionally, you can notice that the block uses skip-connection when the spatial dimensions and channels of the input and output match.

**Comment by yjyoo3312** [comment]
@jleem99 Thank you for checking the implementation!

One miscellenous point for Inverted residual network block is that although we remove activation to final point-wise convolution but still add normalization layer (which meaninfuly govens final classification result as well).
[link](https://github.com/pytorch/vision/blob/6043bc250768b129e90a5321e318c1d51ee48a5c/torchvision/models/mobilenetv2.py#L53)
