### ISSUE TITLE
[lecture9][0521] KNN, an equal number of samples for each class label

### ISSUE THREAD

**Issue by jeonghyunpark2002** [PiLab-CAU/ComputerVision-2401#29]
Hi, professor! I have a question about K-nearest neigbor classifier.

![vision](https://github.com/PiLab-CAU/ComputerVision-2401/assets/92426596/c5e73ec2-5514-49ea-b898-7157f6c85222)

When k = 4, the number of blue label and red label sample is same, as 2.

Then, what is the output of this classifier? Or, how we classify in this case? Is there any additional criteria to determine?

Thank you!

**Comment by yjyoo3312** [comment]
@jeonghyunpark2002 

Thank you for raising that good point! In this case, determining the output results can be very challenging. To avoid this issue, we typically choose an odd number for K, such as 1, 3, or 5.

**Comment by jeonghyunpark2002** [comment]
@yjyoo3312 

Thank you for fast response and a tip to resolve this issue!
