### ISSUE TITLE
[Lecture1][0307] Question about domain of image function in slide number 47.

### ISSUE THREAD

**Issue by cjchangjun** [PiLab-CAU/ComputerVision-2401#3]
![KakaoTalk_Photo_2024-03-11-15-56-47](https://github.com/PiLab-CAU/ComputerVision-2401/assets/92110601/1fc3ba67-78a2-4d74-b7ea-636674188a2c)

This set equation above might for mapping two-dimensional set to one-dimensional set for the domain of image function and i'd like to change little bit for accurate correspondence. 

Is it right to change like above? 
Thank you!

**Comment by yjyoo3312** [comment]
@cjchangjun , thank you for the comment! 
Your correction gets the correct answer. (k=1,..., HW)

One more step, we will concern the python (opencv) format, as:
<img width="1072" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/12525981/ee7b8a17-bfa5-4c87-ad21-e464b9858ae6">
, which is much simpler.
This would be why Python numpy index starts from 0.

I always confuse this indexing, and appreciate your correction! :)
