### ISSUE TITLE
[lecture12][0523] About getting the weight parameter of Bounding Box Regression

### ISSUE THREAD

**Issue by jeonghyunpark2002** [PiLab-CAU/ComputerVision-2401#32]
![issue](https://github.com/PiLab-CAU/ComputerVision-2401/assets/92426596/dfc12419-e29c-404a-bae0-7d4d8bf27b3f)

@yjyoo3312 

Hi, professor! I have question about  getting the weight parameter **w** of Bounding Box Regression.

When calculating w, the equation seems like using MSE loss and ridge regression form.

But you mentioned that the BBox regression is not easy process, so it cannot be solved using just MSE Loss. 

I am confusing about this part. So can you explain a little bit more about this issue?

Thank you!!!

**Comment by yjyoo3312** [comment]
@jeonghyunpark2002 Thank you for the comment!

The loss function uses basic MSE loss and ridge regression, as you mentioned.

But, the important part of this loss function is setting *t*, which is not straightforward.

In Fast-RCNN, the loss changes from MSE+ridge regression to smoothL1 loss, but the setting of *t* remains the same.

**Comment by jeonghyunpark2002** [comment]
Thank you! Now I realized that important part of loss function is setting t, not (MSE + ridge).
