### ISSUE TITLE
[lecture9][0603] Convolutional network parameters

### ISSUE THREAD

**Issue by sumin819** [PiLab-CAU/ComputerVision-2401#33]
![화면 캡처 2024-06-03 220040](https://github.com/PiLab-CAU/ComputerVision-2401/assets/162621982/9c463ca7-5354-4af8-ba9f-77c6a5c7e9f2)

What exactly does this represent? Is this formula correct to indicate how to calculate the output value from the Convolutional Layer and calculate the value at each output location?

Thank you.
Sumin Park

**Comment by yjyoo3312** [comment]
@sumin819 Thank you for the comment!
Yes, this formula correctly describes the operation of the convolution layer, described by PyTorch.

Here is a more detailed explanation of the formula with our convolution example. I think it will be easier to catch the meaning of the equation if we note that **wieght()** is a 4D tensor where the kernel width and height are ommitted.
<img width="1054" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/12525981/6b5f7b26-abe6-4e8d-a6a4-fb24233bfd5f">
