### ISSUE TITLE
[lecture12][0607] About skipping skip-connection in MobileNet v2 (stride =2)

### ISSUE THREAD

**Issue by koallako** [PiLab-CAU/ComputerVision-2401#36]
![KakaoTalk_20240607_085320635](https://github.com/PiLab-CAU/ComputerVision-2401/assets/162315413/79abcd10-2cd1-4380-89c9-4150fa5cdb90)

In MobileNet v2, when the stride is 2, I thought there would be more feature loss than when the stride is 1, so I thought it was necessary to add the input at the end of the part. But why is skip-connection not applied when stride is 2?

Minjung Kim

**Comment by yjyoo3312** [comment]
@koallako 
Thank you for sharing the good point:) When we tested those factors before, the cases skip-connection is applied/not-applied did not have much difference in classification performance in ImageNet classification. I believe these factors were determined through various experiments.
However, note that those characteristics can be different from dataset to dataset.

**Comment by koallako** [comment]
Oh I got it. Thanks for your comment!
