### ISSUE TITLE
[lecture12][0607] Inverted Bottleneck

### ISSUE THREAD

**Issue by sumin819** [PiLab-CAU/ComputerVision-2401#37]
![1](https://github.com/PiLab-CAU/ComputerVision-2401/assets/162621982/00cd5f0a-0baa-4ead-8c79-fee83c6d58af)

The reason for using the traditional bottleneck architecture is to reduce the number of parameters and computational cost. The inverted bottleneck, as I understand it, is illustrated on the right. I am curious if this inverted bottleneck structure, despite the intermediate expansion of channels, affects the number of parameters or computational cost.

Sumin Park
Thank you.

**Comment by yjyoo3312** [comment]
@sumin819 Thank you for commenting the good point!

Yes, the expansion from the inverted bottleneck does impact the number of parameters and computational cost of the 3x3 depthwise (DWC) convolution. However, the parameter size and computational cost of the 3x3 DWC convolution are relatively small, even compared to the 1x1 convolution. Therefore, the expansion has minimal impact when considering the  improvements in classification performance it provides:)

**Comment by nshuhsn** [comment]
I was curious about this too. Thank you for asking!
