### ISSUE TITLE
[lecture10][0610] questions about hidden layer notation

### ISSUE THREAD

**Issue by yewonkim01** [PiLab-CAU/ComputerVision-2401#39]
![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/115199510/6a2f1e2e-e7fa-4c7d-acdb-51de2e296207)

I have a question about the notation in Fully Connected Layer slide, on page 6 of lecture 10. I think the notation "# hidden layer" should be "# hidden units" or "# hidden neurons", because we are calculating the dimensions within a layer.
Is my opinion correct? Or, do we use the two notations interchangeably?

**Comment by yjyoo3312** [comment]
@yewonkim01 Thank you for commenting the typo:) 
Yepp, the term "# hidden units" or "# hidden neurons" is right. I will revise it.
