### ISSUE TITLE
[Lecture10][0611] Small error in lecture slide

### ISSUE THREAD

**Issue by HJH0303** [PiLab-CAU/ComputerVision-2401#41]
![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/89338327/b574b99f-1ba9-45ff-9df4-847d9340a827)
There is a small error in lecture#10 slide p29. I think the sigmoid function formula should be e^(-x).
Thank you.

**Comment by yjyoo3312** [comment]
@HJH0303 Wow, thank you for the correction (what a mistake..),
I will revise the part, then.
