### ISSUE TITLE
[lecture12-2][0612] Small typo in the lecture slide

### ISSUE THREAD

**Issue by goals4292** [PiLab-CAU/ComputerVision-2401#44]
There's a really really minor typo in the lecture slide p27.

![typo](https://github.com/PiLab-CAU/ComputerVision-2401/assets/147023917/cd0f4cd5-4e28-4419-98d2-8327fea38b81) 

As you can see, above slide is incorrectly written as (B, BN), even though it should calculate the IoU of B1 and BN.

Thank you.

**Comment by yjyoo3312** [comment]
@goals4292 Oh, Thank you for the comment, you are correct:)
I will revise it in the final revision.
