### ISSUE TITLE
[lecture9][0614] About the type of convolution

### ISSUE THREAD

**Issue by 423data** [PiLab-CAU/ComputerVision-2401#47]
![KakaoTalk_20240614_232020559](https://github.com/PiLab-CAU/ComputerVision-2401/assets/115198530/21e7721d-b8ce-4ea2-b98a-fc38c4574bad)
![KakaoTalk_20240614_232056012](https://github.com/PiLab-CAU/ComputerVision-2401/assets/115198530/bd077c87-db10-47c9-9a29-cb52787754ce)

**Why is Conv_channel1 on the first slide different from Conv_channel1 on the second slide, but the type of Convolution (name?) that represents them?** (channelwise Conv, pointwise Conv) They have the same components.
Next, **I was wondering what determines the characteristics of each convolution.** At first, I thought it was the components that make up each convolution (like C_in, C_out, ...). I guess the position where the convolution is located has affected it. I look forward to hearing from the expert :)

**Comment by yjyoo3312** [comment]
@423data Thank you for the comment! 

We call 1x1 convolution as Pointwise or Channelwise Convolution. 
For the second question first, main difference of channel-wise (==pointwise == 1x1 conv) and depthwise convolution is summarized in [Issue](https://github.com/PiLab-CAU/ComputerVision-2401/issues/50).

For the first question, upper block is Inverted bottleneck from MobileNet v2, and the bottom one is from MobileNet v1 :) (Aplogies for the confusion)
<img width="666" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/12525981/1d0a0fb6-79c1-43ff-8616-8a88ffc96cf5">
