### ISSUE TITLE
[Lecture12][0617] About Deep Residual Network Architecture

### ISSUE THREAD

**Issue by jwemilee** [PiLab-CAU/ComputerVision-2401#51]
<img width="861" alt="11" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/80567485/4a6a9ad4-1694-4085-b624-1f256463f0e0">
lec 11 45p (with minor typo)
<img width="797" alt="12" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/80567485/bb598ea0-1830-4d11-8973-03672b7421fe">
lec 12 15p

Hello,

I am writing to ask about the differences between the ResNet architectures shown in lecture 12-1 (page 15) and lecture 11 (page 45). It appears that there are discrepancies in the detailed structure of ResNet between the two slides, particularly in terms of the block structure and the filter size of the pooling layer, as highlighted by the boxes in the images. Could you explain the reasons behind these differences?

Thank you for your time.

**Comment by yjyoo3312** [comment]
@jwemilee Thank you for your comment!

Regarding the two pictures, the configuration in lecture 11, slide 45 is correct :) For a more accurate reference, you can check the configuration [here](https://pytorch.org/vision/main/_modules/torchvision/models/resnet.html#resnet50).

I couldn't recall the architecture details without verifying them thoroughly (applogies for the confusion). Regarding the figure in lecture 12, the kernel size of the avgpool before the FC layer should be 7x7 to match the feature size.
