### ISSUE TITLE
[Lecture13][0618] Why use DSSD?

### ISSUE THREAD

**Issue by Kwonminjeong0** [PiLab-CAU/ComputerVision-2401#55]
In studying DSSD, I have a question about why it is used.

In DSSD, upsampling a low-resolution image results in information loss, so why create a higher-resolution image with the loss? Are there features in the lost image that were missed during the downscaling process in the first place?

Could you please provide some insights on this? Thank you.

**Comment by yjyoo3312** [comment]
@Kwonminjeong0 Thank you for the comment!

The advantage of upsampling structures in DSSD is that they increase the depth of the feature map used for detecting smaller images. However, as you mentioned, this kind of upscaling can result in the loss of local information from the original images, typically captured from features near the stem convolution. To address this, DSSD applies skip connections between the feature maps from the downscaling and upscaling processes, as shown in the bottom figure.
<img width="874" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/12525981/326f91f5-777b-4591-9620-b96f37fc91e3">
