### ISSUE TITLE
[Lecture 9] Calculating Output feature size

### ISSUE THREAD

**Issue by junehyeok129** [PiLab-CAU/ComputerVision-2401#56]
<img width="1192" alt="스크린샷 2024-06-18 22 08 27" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/86551630/8e1b5d8a-eeed-4df4-9466-3c7a71a3fd51">

If I calculated the output feature size and the decimal point comes out, how do I deal with the decimal point?

**Comment by sumin819** [comment]
In my opinion, If the result is a decimal, it seems that you should use flooring to discard the decimal part and keep only the integer part.

**Comment by yjyoo3312** [comment]
@junehyeok129 @sumin819 Thank you for the comment and the correct answer:)
