### ISSUE TITLE
[Lecture9][0618] How to reduce Bias

### ISSUE THREAD

**Issue by sumin819** [PiLab-CAU/ComputerVision-2401#57]
PPT 9-1, 54p, 
How to reduce Bias?
==How to reduce underfit?
* choosing a more classifier with more parameters
* Simpler form of data
   - Less number of data
   - Less dimensionality

Here, the reason why we need to make the data simpler is because the model is too simple to capture important patterns in the data, so we want to reduce the number or dimension of the data, leaving only the important features and removing unnecessary features, right?

Thank you
Sumin Park

**Comment by yjyoo3312** [comment]
@sumin819 Thank you for the comment!

Yes, your understanding is correct. Reducing the data dimension, for example by using PCA, reduces the amount of information in the data (expect to remove unnecessary information) and makes it easier for our simple model to analyze. Similarly, removing redundant data can also help our model perform better.
