### ISSUE TITLE
Lecture12 ResNet  1x1 convolution

### ISSUE THREAD

**Issue by junehyeok129** [PiLab-CAU/ComputerVision-2401#58]
I learned from CNN that the use of 1x1 convolution can reduce computational cost. But how did you solve this as I know it affects the learning of spatial information?

**Comment by yjyoo3312** [comment]
@junehyeok129 Thank you for your comment!

As you mentioned, 1x1 convolution can adjust the channel size of the feature map but cannot capture spatial information. Therefore, ResNet (depth >= 50) uses a bottleneck architecture that employs two 1x1 convolutions to reduce and then expand the channel size before and after the standard 3x3 convolution, which can learn spatial information.
