### ISSUE TITLE
[lecture9][0619] Question of depthwise convolution hyperparameters in Mobilenet-v1.

### ISSUE THREAD

**Issue by yonghyun010102** [PiLab-CAU/ComputerVision-2401#59]
Dear Professor,

My name is Yonghyun Jeon, and I am currently enrolled in your Computer Vision class. I am writing to seek clarification regarding a formula on page 68 of Lecture 9_2.

![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/92546000/9f7ae699-077e-4222-b1fe-ade310d7b511)

While I understand that during Depthwise_Conv, the input and output values should maintain the C_in depth to be fed directly into the Conv_channel, I am confused as to why the group parameter is set to C_out. If this is the case, wouldn't each convolution kernel be 
C_out * (C_in/C_out * C_in/C_out * ...), thus negating the depthwise convolution?

Thank you for taking the time to read my question. I look forward to your response.

Best regards,
Yonghyun Jeon

**Comment by yjyoo3312** [comment]
@imsongpasimin Wow, thank you for your comment and for fixing the typo!

As you mentioned, depthwise convolution involves using a group size equal to C_in. Therefore, in the figure, the group size should be C_in, not C_out:)
