### ISSUE TITLE
[Lecture3][0321] Small error in lecture slide

### ISSUE THREAD

**Issue by HJH0303** [PiLab-CAU/ComputerVision-2401#6]
Hello, professor. I'm junhee han , taking a computer vision lecture.
There is a small error in lecture#3 slide p42. I think the (2,3) on the second matrix should be zero.
Thank you.
![IMG_0359](https://github.com/PiLab-CAU/ComputerVision-2401/assets/89338327/f6b84a88-a47c-43c0-ba05-2edeb8bcc68a)

**Comment by yjyoo3312** [comment]
@HJH0303 
(just call me @yjyoo3312 in this repo:) )

Thank you for correcting the slide material! I will reflect the correction into our final slides, uploaded to eClass.
