### ISSUE TITLE
Lecture12  R-CNN Extract region proposals

### ISSUE THREAD

**Issue by junehyeok129** [PiLab-CAU/ComputerVision-2401#60]
I learned that you have to do segmentation in order to do the Region proposal in R-CNN. However,  have to do so much segmentation that there is a resource consumption. Is there any other good way?

**Comment by yjyoo3312** [comment]
@junehyeok129 Thank you for the comment!

In RCNN, an existing non-deep learning-based region proposal method, such as [Selective Search](http://www.huppelen.nl/publications/selectiveSearchDraft.pdf), is used, **not a segmentation method**. In Faster R-CNN, to address the shortcomings of using existing region proposals, a Region Proposal Network (RPN) is introduced, which can be jointly trained with the detection component.
