### ISSUE TITLE
[lecture12-2] [0619] IOU threshold for TP.

### ISSUE THREAD

**Issue by cjchangjun** [PiLab-CAU/ComputerVision-2401#63]
Hello,

I'm little confusing with some concept of making prediction in R-CNN.

I think there are two threshold for processing the result box of R-CNN.
1. Threshold for determining whether our box prediction is positive or not by using conf. score.
2. Threshold for determining whether our positive box prediction is **True positive** or not by using IoU score.

And i just confused with the lecture slide below.
<img width="768" alt="image" src="https://github.com/PiLab-CAU/ComputerVision-2401/assets/92110601/4fe27597-8949-4f60-9caf-3a7830b33e95">

Is it right to change the term **positive** to **True positive**?

Thank you!

**Comment by yjyoo3312** [comment]
@cjchangjun Thank you for the comment! It seems I am a little late, though, 

As you commented, 

- Threshold for determining whether our box prediction is positive or not by using conf. score.
- Threshold for determining whether our positive box prediction is True positive or not by using IoU score.

These two comments are exact, so " positive to True positive" is correct. Thank you for correcting it. :)

**Comment by cjchangjun** [comment]
Thank you!!
