### ISSUE TITLE
[lecture12-2] [0619] Negative prediction in Object Detection prediction.

### ISSUE THREAD

**Issue by cjchangjun** [PiLab-CAU/ComputerVision-2401#65]
Hello,

I have question about Negative prediction in OD task.

I think it is really straightfoward to understand about positive prediction, 
But in the case of negative prediction, it is hard to understand.

In this task, we only predict 'this box is what we want to find!', not kind of like 'this box is not what we want to find...'.

But in this case, we can get (TP + FN) by using the number of gt boxes and TP. So, we can get FN as numerically.

So, I just wonder the term **'negative prediction in Object Detection'** is usually used in cv field.

Thank you!

**Comment by yjyoo3312** [comment]
@cjchangjun Thank you for the comment!

As you noted, negative prediction is not as straightforward as positive prediction. The simplest explanation is that if a certain location does not have a predicted box, it is considered 'negative'. Therefore, True Negative (background regions where our target objects do not exist) is not particularly meaningful. However, if a target object region does not have a predicted box, we can consider the prediction in that region as (False) negative.

Have a nice vacation :)

**Comment by cjchangjun** [comment]
Oh i understand! Thank you for your answer!!
