### ISSUE TITLE
[Lecture9][0619] Quick questions about convolution, etc.

### ISSUE THREAD

**Issue by jleem99** [PiLab-CAU/ComputerVision-2401#67]
Here's just some quick questions!

### Question 1
![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/23395243/c6eea0c0-de4e-4cd4-96f7-6795bf29c8da)
- Does "Channelwise Conv" here mean point-wise convolution (1x1 convolution)?

### Question 2
![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/23395243/c2da7e4c-84d5-43e0-a1c0-29f7fbb18393)
- Does "Channel-wise Avg and Max filtering" mean that the pooling operation is done per channel?
- Then, what does the horizontal red line imply in the right figure of the slide?

### Question 3
![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/23395243/08629770-e8ac-4947-9a04-fa6cfe7d5556)
Just to check the calculation results, Is the following answer correct?:
- O is of shape (128, 16, 16)
- Number of parameters = 3×128×3×3×4 bytes = 13,824 bytes ≈ 0.0132 MiB
- Number of FP operations
  - \# Multiplications per output element = 3×3×3 = 27
  - \# Additions per output element (w/o bias) = 26 (For adding the 27 products from above)
  - \# Output elements = 128×16×16 = 32,768
  - \# Total FP operations = (27+26)×32,768 = 1,736,704

<br/>

Sorry for the late issue, Thank you!
JongHan Leem

**Comment by yjyoo3312** [comment]
@jleem99 Thank you for the comment!

1. Yes, a 1x1 convolution is commonly referred to as pointwise or channelwise convolution.
2. Yes, as you understand, the pooling operation is executed per channel, similar to depthwise convolution. (The red line indicates that the pooling operation does not have parameters—apologies for the confusion.)
3. Yes, your answer is correct. It shows that expanding the kernel size, such as to 11x11, or using a large number of channels requires a huge number of parameters, which can be ineffective. In terms of floating-point (FP) operations, it is worth noting that using high-resolution input increases the number of FP operations.

Have a nice vacation:)
