### ISSUE TITLE
[lecture12-2] [0619] Question about Non-Maximal Suppression Example.

### ISSUE THREAD

**Issue by yonghyun010102** [PiLab-CAU/ComputerVision-2401#68]
Hello professor! I'm quiet curious about the NMS example.

![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/92546000/3830a57c-a93c-41b0-97ae-718b75bab265)

By looking at the illustration, it is evident that only the box with an IoU of 0.7 has been filtered out during the IoU comparison process. This leads to two questions:

1. When performing the box removal process based on the 0.9 box, shouldn't the 0.6 (right) box also be removed, in addition to the 0.7 box, to achieve the prediction as shown in the left image?
2.  If the IoU threshold is high and the 0.6 (right) box was not filtered out, would this 0.6 (right) box remain and be included in the final prediction? Consequently, would there be two prediction boxes for the car on the right side in the left image?

Thank you for taking the time to read my questions!

YongHyeon Jun

**Comment by yjyoo3312** [comment]
@imsongpasimin Thank you for the comment!

1. I think it depends on the setting of the NMS (Non-Maximum Suppression) threshold. Assuming that a box with a confidence score of 0.9 and a box with a confidence score of 0.6 (on the right) have an IOU (Intersection Over Union) of about 0.4, if we set the threshold tighter, we will remove the 0.6 box (on the right).
2. Yes, in our example, the 0.6 box (on the right) will remain in the final representation, which is not adequate. Therefore, setting the NMS threshold is also a critical factor for detection performance.

Have a nice vacation:)
