### ISSUE TITLE
[Lecture4][0326] Questions about fast approximation in Harris corner detection

### ISSUE THREAD

**Issue by jeonghyunpark2002** [PiLab-CAU/ComputerVision-2401#7]
@yjyoo3312 I have a question about fast approximation in harris corner detection! 

![issue1](https://github.com/PiLab-CAU/ComputerVision-2401/assets/92426596/6a2e06a5-5621-4dcf-ac2e-f312370570b0)

As you can see in this figure's highlighted formula, the theta value is computed using eigenvalues of matrix M. 

But you mentioned that the benefit of this fast approximation is We do not need to calculate Eigenvalue. 

How can I understand this part?

Thank you! :)

**Comment by yjyoo3312** [comment]
@jeonghyunpark2002 Sorry for the late reply!

I believe today's course will help the understanding of the questions.

https://github.com/PiLab-CAU/ComputerVision-2401/blob/8e5333a6387887b88dbabe67cff0bad52a0c6165/lecture4/utils.py#L201 
Here's the code snippet. It demonstrates how we compute the response theta, bypassing the need for eigenvalue calculations.

The formula, lamda_1*lambda_2 - alpha(lambda_1+lambda_2)^2, has been deduced by (brilliant) mathematicians to achieve the same result. This allows us to indirectly incorporate our initial criteria for the eigenvalues at the corner points (requiring both to be significant) within the response map, eliminating the necessity to calculate eigenvalues.

Thank you:)

**Comment by jeonghyunpark2002** [comment]
Thank you for the detailed explanation about my question 😄
