### ISSUE TITLE
[Lecture4][0328] Proof of Harris Detector Formulation's approximation

### ISSUE THREAD

**Issue by goals4292** [PiLab-CAU/ComputerVision-2401#8]
Here's the proof of Harris Detector Formulation's approximation by using Taylor expansion

![KakaoTalk_20240329_001518914_02](https://github.com/PiLab-CAU/ComputerVision-2401/assets/147023917/25f0f7e2-1ef0-488d-adb9-ee88bf366f31)
![KakaoTalk_20240329_001518914_01](https://github.com/PiLab-CAU/ComputerVision-2401/assets/147023917/5bcc6543-6b22-427b-802a-bec4fdd1803d)
![proof revise2](https://github.com/PiLab-CAU/ComputerVision-2401/assets/147023917/270833cf-be7f-4ec4-8198-ee01b0190c60)

**Comment by yjyoo3312** [comment]
@goals4292 Thank you for the thorough derivation! With your permission, I'd like to briefly share the problem and its derivation in our lecture.

Much appreciated :)

**Comment by goals4292** [comment]
Thank you for your comment.
Of course, you can share it in the lecture :)
