### ISSUE TITLE
[Lecture2][0403] About impulse functions

### ISSUE THREAD

**Issue by Burugi** [PiLab-CAU/ComputerVision-2401#9]
Hello Professor Youngjoon Yoo

This is a question I asked you in person in a class quite a while ago, and I wanted to write down my question and share it with other students.

![image](https://github.com/PiLab-CAU/ComputerVision-2401/assets/52272632/192219ae-221a-4f45-8f33-533f35b7811d)

The question I asked at the time was, "You said that the impulse function can check the value of the kernel, but in computer vision, we already know the value of the kernel, so why do we need to use the impulse function?

My understanding of the answer was as follows.
'Actually, impulse functions are not only used in computer vision, but also in signal processing, and there is a reason to use impulse functions because they are used in situations where the kernel is not known, but in computer vision, the impulse function is only a mathematical function because it is imported from signal processing.

I'm raising this issue to confirm that my understanding is correct.

Hyunwoong LIM

**Comment by yjyoo3312** [comment]
@Burugi Apologies for the delayed response (it was a department dinnerㅠ). 
In most instances, I agree with your understanding. In computer vision, the use of predefined filters often negates the frequent need for impulse response. However, it's cautious to say whether utilizing impulse response to derive convolution kernels in computer vision is entirely meaningless. For instance, designing operations beyond a simple moving average may present challenges in direct kernel representation, as seen with median filters (does this operation convolutional?). In such cases, verifying whether our operation is linear and shift-invariant becomes essential. If both conditions are met, deriving a kernel via impulse response can be meaningful.

Thank you:)

**Comment by Burugi** [comment]
Thanks for the answer.
I apologize for the late reply.

I see that the impulse function is needed because of the linearity.

Also, thanks for the additional explanation in the lesson.

**Comment by yjyoo3312** [comment]
@Burugi Not at all:) 
Yepp, sometimes, even if an operation works just like convolution should, turning it straight into a kernel isn't always easy. When that happens, using the impulse response can really help, or the case if you're looking for a systemic approach to figure out the kernel.
